name = "TKCBED"
uuid = "be95d4ed-9865-47ce-b7cb-6269c7c4b466"
authors = ["Chen Huang"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
